title: Pavel's Blog
email: pavel@raiskup.cz
description: >
  FLOSS, right?

blog: /blog/

google_analytics: UA-119698614-1

github_username: praiskup

permalink: /blog/:title.html

disqus:
  shortname: praiskup-blog

# Build settings
markdown: kramdown

theme: minima

plugins:
  - jemoji
